blueprint:
  name: Create backup
  description: |
    Creates a backup of your Home Assistant installation.

    You can choose whether you want to create a full Home Assistant system or a partial backup.

    A partial backup will only create a backup of the following:
      - Home Assistant configuration directory
      - Add-ons SSL directory
      - Add-ons share directory
  domain: automation
  source_url: https://github.com/alex3305/home-assistant-blueprints/blob/master/backup.yaml
  input:
    time_trigger:
      name: Time to trigger the backup
      description: The backup will be created at this time
      selector:
        time:
      default: '06:00:00'
    full_backup:
      name: Create a full backup?
      description: When enabled, a full backup will be created. Otherwise only a partial backup is created.
      selector:
        boolean:
      default: true
    every_day:
      name: Run every day of the week?
      description: When enabled, this automation will run every day of the week
      selector:
        boolean: 
      default: true
    backup_day:
      name: Day of the week
      description: When every day is disabled, select a day number to run this automation
      selector:
        number:
          min: 0
          max: 7
          step: 1
          unit_of_measurement: day
          mode: box
      default: 0
    post_backup_action:
      name: Post backup action
      description: Action to perform when the backup has been taken
      selector:
        action:
      default:
        - service: logbook.log
          data:
            name: backup service
            message: backup succesfully created!

mode: single
max_exceeded: silent

variables:
  full_backup_bool: !input full_backup
  every_day_bool: !input every_day
  day_number: !input backup_day

trigger:
  platform: time
  at: !input time_trigger

condition:
  condition: or
  conditions:
    - "{{ every_day_bool }}"
    - condition: and
      conditions:
        - "{{ not every_day_bool }}"
        - "{{ ((day_number | int) - 1) == (now().weekday() | int) }}"

action:
  - choose:
      - conditions: "{{ full_backup_bool }}"
        sequence:
          service: hassio.backup_full
          data:
            name: "Automated full backup {{ now().strftime('%Y-%m-%d') }}"
      - conditions: "{{ not full_backup_bool }}"
        sequence:
          service: hassio.backup_partial
          data:
            name: "Automated partial backup {{ now().strftime('%Y-%m-%d') }}"
            folders:
              - homeassistant
              - ssl
              - share
  - choose:
    default: !input post_backup_action
