blueprint:
  name: Signify Hue Dimmer Switch (RWL022)
  description: |
    Blueprint that utilizes a Signify Hue Dimmer Switch (RWL022) from the deCONZ integration to control one or more lights.

     ➡ Pressing the | button will turn the light on
     ➡ Pressing the 🔆 button will increase the brightness with 5%
     ➡ Pressing the 🔅 button will decrease the brightness with 5%
     ➡ Pressing the ⚪ button will turn the light off

     ➡ Holding the increase brightness button will continuously increase the brightness with a single step
     ➡ Holding the decrease brightness button will continuously decrease the brightness with a single step
  domain: automation
  source_url: https://github.com/alex3305/home-assistant-blueprints/blob/master/deconz_philips_rwl021.yaml
  input:
    dimmer_switch:
      name: Signify Hue Dimmer Switch (RWL022)
      description: Philips Hue Dimmer Switch to use
      selector:
        device: 
          integration: deconz
          manufacturer: Signify Netherlands B.V.
          model: RWL022
    light_target:
      name: Light
      description: Light or lights to control with the remote control
      selector:
        target:
          entity:
            domain: light

mode: queued
max_exceeded: silent

trigger:
  platform: event
  event_type: deconz_event
  event_data:
    device_id: !input dimmer_switch

action:
  choose:
      # Toggle button press
    - conditions: "{{ (trigger.event.data.event | int) == 1002 }}"
      sequence:
        service: light.toggle
        target: !input light_target
      # Increase brightness button press
    - conditions: "{{ (trigger.event.data.event | int) == 2002 }}"
      sequence:
        service: light.turn_on
        target: !input light_target
        data:
          brightness_step_pct: 5
      # Decrease brightness button press
    - conditions: "{{ (trigger.event.data.event | int) == 3002 }}"
      sequence:
        service: light.turn_on
        target: !input light_target
        data:
          brightness_step_pct: -5
      # Increase brightness button hold
    - conditions: "{{ (trigger.event.data.event | int) == 2001 }}"
      sequence:
        service: light.turn_on
        target: !input light_target
        data:
          brightness_step: 1
      # Decrease brightness button hold
    - conditions: "{{ (trigger.event.data.event | int) == 3001 }}"
      sequence:
        service: light.turn_on
        target: !input light_target
        data:
          brightness_step: -1
      # TODO Implement Hue button
