blueprint:
  name: IKEA TRÅDFRI Remote Control
  description: |
    Blueprint that utilizes an IKEA TRÅDFRI Remote Control from the deCONZ integration to control one or more lights.

     ➡ Pressing the on/off button will toggle the lights
     ➡ Pressing the 🔆 button will increase the brightness with 5%
     ➡ Pressing the 🔅 button will decrease the brightness with 5%
     ➡ Pressing the ◀ button will activate the action(s) you have selected
     ➡ Pressing the ▶ button will activate the action(s) you have selected
  domain: automation
  source_url: https://github.com/alex3305/home-assistant-blueprints/blob/master/deconz_tradfri_remote_control.yaml
  input:
    remote:
      name: IKEA TRÅDFRI Remote Control
      description: IKEA TRÅDFRI Remote Control to utilize
      selector:
        device:
          integration: deconz
          manufacturer: IKEA of Sweden
          model: TRADFRI remote control
    light_target:
      name: Light
      description: Light or lights to control with the remote control
      selector:
        target:
          entity:
            domain: light
    left_action:
      name: Left button action(s)
      description: Custom action(s) for the left button
      selector:
        action:
    right_action:
      name: Right button action(s)
      description: Custom action(s) for the right button
      selector:
        action:

mode: queued
max_exceeded: silent

trigger:
  platform: event
  event_type: deconz_event
  event_data:
    device_id: !input remote

action:
  choose:
      # On/off button press
    - conditions: "{{ (trigger.event.data.event | int) == 1002 }}"
      sequence:
        service: light.toggle
        target: !input light_target
      # Increase brightness button press
    - conditions: "{{ (trigger.event.data.event | int) == 2002 }}"
      sequence:
        service: light.turn_on
        target: !input light_target
        data:
          brightness_step_pct: 5
      # Decrease brightness button press
    - conditions: "{{ (trigger.event.data.event | int) == 3002 }}"
      sequence:
        service: light.turn_on
        target: !input light_target
        data:
          brightness_step_pct: -5
      # Left button press
    - conditions: "{{ (trigger.event.data.event | int) == 4002 }}"
      sequence: !input left_action
      # Right button press
    - conditions: "{{ (trigger.event.data.event | int) == 5002 }}"
      sequence: !input right_action
